config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'contact', to: 'static_pages#contact'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]

  resources :posts do
    collection do
      get :likes
    end
  end

  resources :toppings do
    get 'posts', to: 'posts#search'
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/noodle.rb
class Noodle < ApplicationRecord
  has_many :post_noodles, dependent: :destroy, foreign_key: 'noodle_id'

  has_many :posts, through: :post_noodles
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  has_many :post_noodles, dependent: :destroy
  has_many :noodles, through: :post_noodles

  has_many :post_toppings, dependent: :destroy
  has_many :toppings, through: :post_toppings

  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :topping, presence: true
  validates :image, presence: true
  validates :content, length: { maximum: 65535 }

  def save_topping(sent_toppings)
    current_toppings = self.toppings.pluck(:name) unless self.toppings.nil?
    old_toppings = current_toppings - sent_toppings
    new_toppings = sent_toppings - current_toppings

    old_toppings.each do |old|
      self.toppings.delete Topping.find_by(name: old)
    end

    new_toppings.each do |new|
      new_post_topping = Topping.find_or_create_by(name: new)
      self.toppings << new_post_topping
    end
  end
end

app/models/post_noodle.rb
class PostNoodle < ApplicationRecord
  belongs_to :post
  belongs_to :noodle

  validates :post_id, presence: true
  validates :noodle_id, presence: true
end

app/models/post_topping.rb
class PostTopping < ApplicationRecord
  belongs_to :post
  belongs_to :topping
  
  validates :post_id, presence: true
  validates :topping_id, presence: true
end

app/models/topping.rb
class Topping < ApplicationRecord
  has_many :post_toppings, dependent: :destroy, foreign_key: 'topping_id'

  has_many :posts, through: :post_toppings

  validates :name, uniqueness: true, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, uniqueness: true, presence: true, length: { maximum: 255 }

  def own?(object)
    id == object.user_id
  end

  def like(post)
    like_posts << post
  end

  def unlike(post)
    like_posts.destroy(post)
  end

  def like?(post)
    like_posts.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    current_user.like(@post)
    # redirect_to posts_path
  end

  def destroy
    @post = current_user.likes.find(params[:id]).post
    current_user.unlike(@post)
    # redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @topping_list = Topping.all
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new 
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    topping_list = params[:post][:topping].split(',')
    if @post.save
      @post.save_topping(topping_list)
      redirect_to posts_path, success: t('posts.create.success')
    else
      flash.now[:'danger'] = t('posts.create.fail')
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @post.toppings = @post.toppings
  end

  def edit
    @post = current_user.posts.find(params[:id])
    @topping_list = @post.toppings.pluck(:name).join(',')
  end

  def update
    @post = current_user.posts.find(params[:id])
    topping_list = params[:post][:topping].split(',')
    if @post.update(post_params)
      @post.save_topping(topping_list)
      redirect_to post_path(@post), success: t('defaults.message.updated')
    else
      flash.now['danger'] = t('defaults.message.not_updated')
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: t('defaults.message.deleted')
  end

  def likes
    @posts = current_user.likes_posts
  end

  def search
    @topping_list = Topping.all
    @topping = Topping.find(params[:topping_id])
    @posts = @topping.posts.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :topping, :image, :image_cache, :content)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path, success: 'ユーザーを更新しました'
    else
      flash.now[:danger] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  def show
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :avatar_cache)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end

  def terms; end

  def privacy; end

  def contact; end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'ズボラーメン'

    page_title.empty? ? base_title : page_title + " | " + base_title
  end
  
  def default_meta_tags
    {
      site: 'ズボラーメン',
      title: 'ズボラなあなたへの超簡単カップラーメントッピング共有サービス',
      reverse: true,
      charset: 'utf-8',
      description: 'ズボラな人でも簡単に変化を楽しめるカップラーメンのトッピング共有サービスです。',
      keywords: 'カップラーメン,カップ麺,トッピング,ズボラ,超簡単,アレンジ',
      canonical: request.original_url,
      separator: '|',
      
      og: {
        site_name: 'ズボラーメン',
        title: 'ズボラなあなたへの超簡単カップラーメントッピング共有サービス',
        description: 'ズボラな人でも簡単に変化を楽しめるカップラーメンのトッピング共有サービスです。',
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.jpg'),
        local: 'ja-JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@9110_yasu',
        image: image_url('ogp.jpg'),
      }
    }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    
    <%= display_meta_tags(default_meta_tags) %>

    <script src="https://kit.fontawesome.com/a8b05bc380.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= render 'shared/bottom_navbar' if logged_in? %>
  </body>
</html>

app/views/likes/create.js.erb
$("#js-like-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/unlike', post: @post)) %>");

app/views/likes/destroy.js.erb
$("#js-like-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/like', post: @post)) %>");

app/views/posts/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: "button-edit-#{post.id}", class: "link-success"  do %>
      <i class="fa-solid fa-pen"></i>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), id: "button-delete-#{post.id}", class: "link-danger", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <i class="fa-solid fa-trash"></i>
    <% end %>
  </li>
</ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group text-center mb-3">
    <%= f.label :title %>
    <span class="badge text-bg-danger">必須</span>
    <%= f.collection_select :title, Noodle.all, :name, :name, { include_blank: '商品名を選択してください' },  class: 'form-control' %> 
  </div>
  <div class="form-group text-center mb-3">
    <%= f.label :topping %>
    <span class="badge text-bg-danger">必須</span>
    <%= f.text_field :topping, value: @topping_list, class: 'form-control', placeholder: ',で区切って入力してください' %>
  </div>
  <div class="form-group text-center mb-3">
    <%= f.label :image %>
    <span class="badge text-bg-danger">必須</span>
    <%= f.file_field :image, class: 'form-control mb-3', accept: 'image/*' %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class='text-center mt-4 mb-4'>
    <%= image_tag post.image_url, id: 'preview', size: '300x200' %>
  </div>
  <div class="form-group text-center mb-3">
    <%= f.label :content %>
    <span class="badge text-bg-secondary">任意</span>
    <%= f.text_area :content, class: 'form-control', placeholder: 'コメント、美味しいポイントなど、お好きな内容をお書きください', rows: 10 %>
  </div>
  <div class="text-center">
  <%= f.submit t('defaults.post'), class: 'btn btn-warning' %>
<% end %>

app/views/posts/_like.html.erb
<%= link_to likes_path(post_id: post.id), id: "js-like-button-for-post-#{post.id}", class:"float-right", method: :post, remote: true do %>
  <i class="fa-regular fa-thumbs-up" style="color: black;"></i>
  <span style="color: black;"><%= post.likes.count %></span>
  <p style="color: black;">これおいしい！</p>
<% end %>

app/views/posts/_like_button.html.erb
<% if current_user.like?(post) %>
  <%= render 'unlike', { post: post } %>
<% else %>
  <%= render 'like', { post: post } %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="card">
      <%= image_tag post.image_url, class: 'card-img-top', size: '300x200' %>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to post.title, post_path(post), class: "link-dark" %>
        </h4>
        <ul class="list-inline">
          <li class="card-text">
            <i class="fa-solid fa-tags"></i>
            <% post.toppings.each do |topping| %>
              <%= link_to topping.name, topping_posts_path(topping_id: topping.id), class: "badge rounded-pill bg-warning text-dark" %>
            <% end %>
          </li>
          <li class="card-text">
            <i class="fa-solid fa-comments"></i>
            <%= post.content %>
          </li>
          <li class="card-text">
            <i class="fa-solid fa-user"></i>
            <%= post.user.name %>
          </li>
          <li class="card-text">
            <i class="fa-regular fa-calendar-days"></i>
            <%= l post.created_at, format: :long %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :title_or_content_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
    <div class="input-group-append">
      <%= f.submit class: 'btn btn-warning' %>
    </div>
  </div>
<% end %>

app/views/posts/_twitter.html.erb
<div class="list-inline-item"> 
  <%= link_to "https://twitter.com/share?url=#{ request.url }&text=【おすすめのトッピング】%0a#{ post.title }に合うトッピングを共有します！%0a「#{ post.topping }」
  %0a%0a&hashtags=カップラーメン,カップ麺,トッピング,ズボラ,超簡単,アレンジ,カップラーメン好きと繋がりたい", 
  target: '_blank' do %>
    <i class="fab fa-twitter" style='color: #3399FF;'></i>
    <span>この投稿をTwitterでシェア</span>
  <% end %>
</div>

app/views/posts/_unlike.html.erb
<%= link_to like_path(current_user.likes.find_by(post_id: post.id)), id: "js-like-button-for-post-#{post.id}", class:"float-right", method: :delete, remote: true do %>
  <i class="fa-solid fa-thumbs-up" style="color: #f4be9b;"></i>
  <%= post.likes.count %>
  <p style="color: black;">これおいしい！</p>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-11 col-lg-7 mx-auto">
      <div class="card shadow">
        <div class="card-body p-4 p-sm-5">
          <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
          <%= render 'form', { post: @post } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-12">
      <%= render 'search_form', url: posts_path %>
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-11 col-lg-7 mx-auto">
      <div class="card shadow">
        <div class="card-body p-4 p-sm-5">
          <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
          <%= render 'form', { post: @post } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="container pt-3">
  <div class="row">
    <%= render @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
    <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
      <div class="row justify-content-center">
        <%= image_tag @post.image.url, class: 'card-img-top img-fluid', size: '300x200' %>
      </div>
      
      <div class="card mb-3 mb-lg-0">
        <div class="card-body">
          <h5 class="fa-solid fa-pen"> 商品名</h5>
          <div><%= @post.title %></div>
          <hr>

          <h5 class="fa-solid fa-tags"> トッピング</h5>
          <br>
          <% @post.toppings.each do |topping| %>
            <%= link_to topping.name, topping_posts_path(topping_id: topping.id), class: "badge rounded-pill bg-warning text-dark" %>
          <% end %>
          <hr>
            
          <h5 class="fa-solid fa-comments"> 本文</h5>
          <div><%= @post.content %></div>
          <hr>
            
          <p class="fa-solid fa-user"> by <%= @post.user.name %></p>
          <br>

          <p class="fa-regular fa-calendar-days"> <%= l @post.created_at, format: :long %></p>
          <br>

          <% if current_user.own?(@post) %>
            <%= render 'twitter', post: @post  %>
            <%= render 'crud_menus', post: @post %>
          <% else %>
            <%= render 'like_button', post: @post  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-10 col-lg-6 mx-auto">
      <div class="card shadow my-5">
        <div class="card-body p-4 p-sm-5">
          <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
          <%= form_with model: @user, url: profile_path, local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="text-center mb-3">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control mb-3' %>
            </div>
            <div class="text-center mb-3">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control mb-3' %>
            </div>
            <div class="text-center mb-3">
              <%= f.label :avatar %>
              <%= f.file_field :avatar, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
              <%= f.hidden_field :avatar_cache %>
            </div>
            <div class='text-center mt-3 mb-3'>
              <%= image_tag @user.avatar.url, class: 'rounded-circle', id: 'preview', size: '100x100' %>
            </div>
            <div class="text-center mb-3">
              <%= f.submit class: 'btn btn-warning' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-10 col-lg-6 mx-auto">
      <div class="card shadow my-5">
        <div class="card-body p-4 p-sm-5">
          <p class='text-center mb-4 fw-light fs-2'><%= t('.title') %></p>
          <table class="table">
            <tr>
              <th scope="row"><%= t(User.human_attribute_name(:email)) %></th>
              <td><%= current_user.email %></td>
            </tr>
            <tr>
              <th scope="row"><%= t(User.human_attribute_name(:name)) %></th>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <th scope="row"><%= t(User.human_attribute_name(:avatar)) %></th>
              <td><%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '50x50' %></td>
            </tr>
          </table>
          <div class="text-center mb-3">
              <%= link_to t('defaults.edit'), edit_profile_path, class: 'btn btn-success' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'logo.png' %>
      <% end %>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to (t 'defaults.sign_up'), new_user_path, class: 'nav-link text-dark fw-bold' %>
        </li>
        <li class="nav-item">
          <%= link_to (t 'defaults.login'), login_path, class: 'nav-link text-dark fw-bold' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_bottom_navbar.html.erb
<div class="container-fluid">
  <div class="row bg-light">
    <nav class="nav justify-content-center fixed-bottom bg-light copyright">
      <%= link_to root_path, class: 'nav-link text-dark' do %>
        <div class="text-center m-3">
          <i class="fa-solid fa-house"></i>
          <p>ホーム</p>
        </div>
      <% end %>
      <%= link_to posts_path, class: 'nav-link text-dark' do %>
        <div class="text-center m-3">
          <i class="fa-solid fa-magnifying-glass"></i>
          <p>投稿一覧</p>
        </div>
      <% end %>
      <%= link_to new_post_path, class: 'nav-link text-dark' do %>
        <div class="text-center m-3">
          <i class="fa-solid fa-camera-retro"></i>
          <p>投稿作成</p>
        </div>
      <% end %>
      <%= link_to profile_path, class: 'nav-link text-dark' do %>
        <div class="text-center m-3">
          <i class="fa-solid fa-address-card"></i>
          <p>プロフィール</p>
        </div>
      <% end %>
    </nav>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="pt-5 pb-2 mb-5">
  <div class="container-fluid">
    <div class="pt-5 mb-5 pb-5 border-top border-dark">
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <%= link_to "利用規約", terms_path, class: 'nav-link text-dark fw-bold' %>
        </li>
        <li class="nav-item">
          <%= link_to "プライバシーポリシー", privacy_path, class: 'nav-link text-dark fw-bold' %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", contact_path, class: 'nav-link text-dark fw-bold' %>
        </li>
      </ul>
      <div class="pt-3">
      <p class="text-center text-muted">Copyright © 2023. ズボラーメン</p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'logo.png' %>
      <% end %>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to t('defaults.logout'), logout_path, class: 'nav-link text-dark fw-bold', method: :delete %>
        </li>
        <li class="nav-item">
          <%= image_tag current_user.avatar.url, size: '40x40', class: 'rounded-circle mr15' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-4">
  <div class="row">
    <div class="col-md-10 col-lg-6 mx-auto">
      <div class="card shadow my-5">
        <div class="card-body p-4 p-sm-5">
          <p class='text-center mb-4 fw-light fs-2'><%= t('user_sessions.new.title') %></p>
          <%= form_with url: login_path, local: true do |f| %>
            <div class="form-group text-center mb-4">
              <i class="fa-solid fa-envelope"></i>
              <%= f.label :email, User.human_attribute_name(:email) %>
              <%= f.text_field :email, class: 'form-control', placeholder: 'メールアドレスを入力してください' %>
            </div>
            <div class="form-group text-center mb-4">
              <i class="fa-solid fa-lock"></i>
              <%= f.label :password, User.human_attribute_name(:password) %>
              <%= f.password_field :password, class: 'form-control', placeholder: 'パスワードを入力してください' %>
            </div>
            <div class="text-center mb-4">
              <%= f.submit t('defaults.login'), class: 'btn btn-warning' %>
            </div>
            <div class='text-center mb-4'>
              <%= link_to t('.to_register_page'), new_user_path %>
              <a href="#"><%= t('.password_forget') %></a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>